# Base URL
baseURL: "https://withblue.ink/"

# Ignore files
ignoreFiles:
  - "\\.sh$"
  - "Makefile"
  - "Dockerfile"

# Default language
languageCode: "en-us"

# Basic metadata
title: "With Blue Ink"
copyright: "Unless otherwise noted, all blog posts, photos, graphics, presentations and other media and assets are copyrighted work with all rights reserved. Unless otherwise noted, all code snippets are available under the Unlicense."
author: "Alessandro Segala"

# Custom params
params:
  # Enable debug views
  debugView: false
  # Enable comments
  comments: true
  # Site description
  description: "A blog by Alessandro Segala (@ItalyPaleAle)"
  # Fathom Analytics
  FathomAnalytics:
    Endpoint: st.italypaleale.me
    SiteID: PGLNG
  # Plausible Analytics
  PlausibleAnalytics:
    Endpoint: pls.italypaleale.me
    Domain: withblue.ink

# Theme configuration
theme: "withblueink"
paginate: 15

# Enable all URLs to be relative, and make them end with ".html"
relativeURLs: true
canonifyURLs: false
uglyurls: true

# Format for posts' permalinks
permalinks:
  posts: /:year/:month/:day/:slug

# Disable taxonomies
disableKinds:
  - term
  - taxonomy
  - taxonomyTerm
  - section

# RSS
rssLimit: 10
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Google Analytics
#GoogleAnalytics: "UA-72379106-1"

# Privacy
privacy:
  youtube:
    privacyEnhanced: true
  twitter:
    enableDNT: true

# Markup converters and syntax highlighter
markup:
  #defaultMarkdownHandler: blackFriday
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
