# Site settings
title: With Blue Ink
header-img: img/home-bg.jpg
email: alessandro@withblueink.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://withblue.ink"
twitter_username: EgoAleSum
github_username:  EgoAleSum
linkedin_username: alessandrosegala
#facebook_username:  IronSummitMedia

# Build settings
gems: 
  - "jekyll-paginate"
  - "jekyll-redirect-from"
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: 
  - "less"
  - "node_modules"
  - "Gruntfile.js"
  - "package.json"
  - "README.md"
  - "LICENSE.md"
