# Site settings
title: With Blue Ink
header-img: img/home-bg.jpg
email: alessandro@withblueink.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "https://withblue.ink"
twitter_username: EgoAleSum
github_username:  EgoAleSum
linkedin_username: alessandrosegala
#email_address:  your-email@yourdomain.com
analytics: true

# Build settings
plugins: 
  - "jekyll-paginate"
  - "jekyll-redirect-from"
  - "jekyll-sitemap"
markdown: kramdown
highlighter: pygments
permalink: "/:year/:month/:day/:title.html"
paginate: 10
exclude: 
  - "less"
  - "node_modules"
  - "Makefile"
  - "Gruntfile.js"
  - "package.json"
  - "package-lock.json"
  - "utils"
  - "README.md"
  - "LICENSE.md"
  - "assets-source"
  - "Gemfile"
  - "Gemfile.lock"
  - "Dockerfile"
  - "docker"
