# Base URL
baseURL: "https://withblue.ink/"

# Ignore files
ignoreFiles:
- "\\.sh$"
- "Makefile"
- "Dockerfile"

# Default language
languageCode: "en-us"

# Basic metadata
title: "With Blue Ink"
copyright: "Unless otherwise noted, all blog posts, photos, graphics, presentations and other media are published under a Creative Commons Attribution-NonCommercial (CC BY-NC) license. Unless otherwise noted, all code snippets are available under the Unlicense."
author: "Alessandro Segala"
params:
  description: "Tales of surfing the Cloud"

# Theme configuration
theme: "clean-blog"
paginate: 10

# Enable all URLs to be relative, and make them end with ".html"
relativeURLs: true
canonifyURLs: false
uglyurls: true

# Format for posts' permalinks
permalinks:
  post: /:year/:month/:day/:slug

# Disable taxonomies
disableKinds:
- taxonomy
- taxonomyTerm
- section

# RSS
rssLimit: 10
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Google Analytics
GoogleAnalytics: "UA-72379106-1"

# Syntax highlighting
pygmentsCodeFences: true
pygmentsStyle: "tango"

# Privacy
privacy:
  youtube:
    privacyEnhanced: true

# Menu (Not implemented)
menu:
  main:
    - name: "Home"
      url: "/"
    - name: "About"
      url: "/about.html"